<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Services\RbacCacheService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            // ==========================================
            // 1. Core Identity & Dashboard
            // ==========================================
            [
                'code' => 'dashboard.view',
                'name' => 'View Dashboard',
                'module' => 'dashboard',
                'resource' => 'dashboard',
                'action' => 'view',
                'description' => 'Can view identity and business dashboard metrics',
            ],

            // Users Management
            [
                'code' => 'users.view',
                'name' => 'View Users',
                'module' => 'users',
                'resource' => 'users',
                'action' => 'view',
                'description' => 'Can view users list and details',
            ],
            [
                'code' => 'users.create',
                'name' => 'Create Users',
                'module' => 'users',
                'resource' => 'users',
                'action' => 'create',
                'description' => 'Can create users',
            ],
            [
                'code' => 'users.update',
                'name' => 'Update Users',
                'module' => 'users',
                'resource' => 'users',
                'action' => 'update',
                'description' => 'Can update user profiles and credentials',
            ],
            [
                'code' => 'users.delete',
                'name' => 'Delete Users',
                'module' => 'users',
                'resource' => 'users',
                'action' => 'delete',
                'description' => 'Can delete users',
            ],
            [
                'code' => 'users.manage',
                'name' => 'Full User Management',
                'module' => 'users',
                'resource' => 'users',
                'action' => 'manage',
                'description' => 'Can perform all user administrative actions',
            ],

            // ==========================================
            // 2. Roles & Permissions (RBAC)
            // ==========================================
            [
                'code' => 'roles.view',
                'name' => 'View Roles',
                'module' => 'roles',
                'resource' => 'roles',
                'action' => 'view',
                'description' => 'Can view roles',
            ],
            [
                'code' => 'roles.create',
                'name' => 'Create Roles',
                'module' => 'roles',
                'resource' => 'roles',
                'action' => 'create',
                'description' => 'Can create roles',
            ],
            [
                'code' => 'roles.update',
                'name' => 'Update Roles',
                'module' => 'roles',
                'resource' => 'roles',
                'action' => 'update',
                'description' => 'Can update roles',
            ],
            [
                'code' => 'roles.delete',
                'name' => 'Delete Roles',
                'module' => 'roles',
                'resource' => 'roles',
                'action' => 'delete',
                'description' => 'Can delete roles',
            ],
            [
                'code' => 'roles.manage',
                'name' => 'Full Role Management',
                'module' => 'roles',
                'resource' => 'roles',
                'action' => 'manage',
                'description' => 'Can perform all role administrative actions',
            ],
            [
                'code' => 'user_roles.assign',
                'name' => 'Assign User Roles',
                'module' => 'roles',
                'resource' => 'user_roles',
                'action' => 'assign',
                'description' => 'Can assign roles to users',
            ],
            [
                'code' => 'user_roles.remove',
                'name' => 'Remove User Roles',
                'module' => 'roles',
                'resource' => 'user_roles',
                'action' => 'remove',
                'description' => 'Can remove roles from users',
            ],
            [
                'code' => 'permissions.view',
                'name' => 'View Permissions',
                'module' => 'permissions',
                'resource' => 'permissions',
                'action' => 'view',
                'description' => 'Can view permissions',
            ],
            [
                'code' => 'permissions.create',
                'name' => 'Create Permissions',
                'module' => 'permissions',
                'resource' => 'permissions',
                'action' => 'create',
                'description' => 'Can create permissions',
            ],
            [
                'code' => 'permissions.update',
                'name' => 'Update Permissions',
                'module' => 'permissions',
                'resource' => 'permissions',
                'action' => 'update',
                'description' => 'Can update permissions',
            ],
            [
                'code' => 'permissions.delete',
                'name' => 'Delete Permissions',
                'module' => 'permissions',
                'resource' => 'permissions',
                'action' => 'delete',
                'description' => 'Can delete permissions',
            ],

            // ==========================================
            // 3. POS PIN Terminal Authentication
            // ==========================================
            [
                'code' => 'pos_pin.view',
                'name' => 'View POS PIN Status',
                'module' => 'pos_pin',
                'resource' => 'pin',
                'action' => 'view',
                'description' => 'Can view POS PIN status',
            ],
            [
                'code' => 'pos_pin.update',
                'name' => 'Update POS PIN',
                'module' => 'pos_pin',
                'resource' => 'pin',
                'action' => 'update',
                'description' => 'Can update cashier POS PIN',
            ],
            [
                'code' => 'pos_pin.verify',
                'name' => 'Verify POS PIN',
                'module' => 'pos_pin',
                'resource' => 'pin',
                'action' => 'verify',
                'description' => 'Can quick-verify POS PIN at terminal',
            ],
            [
                'code' => 'pos_pin.manage',
                'name' => 'Full POS PIN Management',
                'module' => 'pos_pin',
                'resource' => 'pin',
                'action' => 'manage',
                'description' => 'Can manage cashier PINs',
            ],

            // ==========================================
            // 4. Devices & Sessions Security
            // ==========================================
            [
                'code' => 'sessions.view',
                'name' => 'View Sessions',
                'module' => 'sessions',
                'resource' => 'sessions',
                'action' => 'view',
                'description' => 'Can view user sessions',
            ],
            [
                'code' => 'sessions.revoke',
                'name' => 'Revoke Sessions',
                'module' => 'sessions',
                'resource' => 'sessions',
                'action' => 'revoke',
                'description' => 'Can revoke user sessions',
            ],
            [
                'code' => 'devices.view',
                'name' => 'View Devices',
                'module' => 'devices',
                'resource' => 'devices',
                'action' => 'view',
                'description' => 'Can view user devices',
            ],
            [
                'code' => 'devices.trust',
                'name' => 'Trust Devices',
                'module' => 'devices',
                'resource' => 'devices',
                'action' => 'trust',
                'description' => 'Can mark user devices as trusted',
            ],
            [
                'code' => 'devices.block',
                'name' => 'Block Devices',
                'module' => 'devices',
                'resource' => 'devices',
                'action' => 'block',
                'description' => 'Can block devices',
            ],
            [
                'code' => 'devices.manage',
                'name' => 'Full Device Management',
                'module' => 'devices',
                'resource' => 'devices',
                'action' => 'manage',
                'description' => 'Can manage device trust and security status',
            ],

            // ==========================================
            // 5. Security Events & Audit Trail
            // ==========================================
            [
                'code' => 'login_attempts.view',
                'name' => 'View Login Attempts',
                'module' => 'security',
                'resource' => 'login_attempts',
                'action' => 'view',
                'description' => 'Can view login attempts and security logs',
            ],
            [
                'code' => 'security_events.view',
                'name' => 'View Security Audit Events',
                'module' => 'security',
                'resource' => 'security_events',
                'action' => 'view',
                'description' => 'Can view forensic security audit trail logs',
            ],
            [
                'code' => 'security_events.export',
                'name' => 'Export Security Audit Events',
                'module' => 'security',
                'resource' => 'security_events',
                'action' => 'export',
                'description' => 'Can export forensic security audit events for external analysis',
            ],
            [
                'code' => 'security_events.manage',
                'name' => 'Manage Security Events & Alerts',
                'module' => 'security',
                'resource' => 'security_events',
                'action' => 'manage',
                'description' => 'Can configure security alerts and manage audit policies',
            ],

            // ==========================================
            // 6. Businesses, Outlets & POS Hardware
            // ==========================================
            [
                'code' => 'businesses.view',
                'name' => 'View Businesses',
                'module' => 'businesses',
                'resource' => 'businesses',
                'action' => 'view',
                'description' => 'Can view business profiles and details',
            ],
            [
                'code' => 'businesses.create',
                'name' => 'Create Businesses',
                'module' => 'businesses',
                'resource' => 'businesses',
                'action' => 'create',
                'description' => 'Can create new businesses',
            ],
            [
                'code' => 'businesses.update',
                'name' => 'Update Businesses',
                'module' => 'businesses',
                'resource' => 'businesses',
                'action' => 'update',
                'description' => 'Can update business details and settings',
            ],
            [
                'code' => 'businesses.delete',
                'name' => 'Delete Businesses',
                'module' => 'businesses',
                'resource' => 'businesses',
                'action' => 'delete',
                'description' => 'Can delete businesses',
            ],
            [
                'code' => 'business_users.view',
                'name' => 'View Business Users',
                'module' => 'business_users',
                'resource' => 'business_users',
                'action' => 'view',
                'description' => 'Can view users assigned to a business',
            ],
            [
                'code' => 'business_users.manage',
                'name' => 'Manage Business Users',
                'module' => 'business_users',
                'resource' => 'business_users',
                'action' => 'manage',
                'description' => 'Can add, update, suspend, or remove users in a business',
            ],
            [
                'code' => 'business_settings.view',
                'name' => 'View Business Settings',
                'module' => 'business_settings',
                'resource' => 'business_settings',
                'action' => 'view',
                'description' => 'Can view business configuration and settings',
            ],
            [
                'code' => 'business_settings.update',
                'name' => 'Update Business Settings',
                'module' => 'business_settings',
                'resource' => 'business_settings',
                'action' => 'update',
                'description' => 'Can update business configuration and preferences',
            ],
            [
                'code' => 'outlets.view',
                'name' => 'View Outlets',
                'module' => 'outlets',
                'resource' => 'outlets',
                'action' => 'view',
                'description' => 'Can view outlet locations',
            ],
            [
                'code' => 'outlets.create',
                'name' => 'Create Outlets',
                'module' => 'outlets',
                'resource' => 'outlets',
                'action' => 'create',
                'description' => 'Can create new outlets for a business',
            ],
            [
                'code' => 'outlets.update',
                'name' => 'Update Outlets',
                'module' => 'outlets',
                'resource' => 'outlets',
                'action' => 'update',
                'description' => 'Can update outlet settings and details',
            ],
            [
                'code' => 'outlets.delete',
                'name' => 'Delete Outlets',
                'module' => 'outlets',
                'resource' => 'outlets',
                'action' => 'delete',
                'description' => 'Can delete outlets',
            ],
            [
                'code' => 'registers.view',
                'name' => 'View Registers',
                'module' => 'registers',
                'resource' => 'registers',
                'action' => 'view',
                'description' => 'Can view cash registers and points of sale',
            ],
            [
                'code' => 'registers.create',
                'name' => 'Create Registers',
                'module' => 'registers',
                'resource' => 'registers',
                'action' => 'create',
                'description' => 'Can create new cash registers for an outlet',
            ],
            [
                'code' => 'registers.update',
                'name' => 'Update Registers',
                'module' => 'registers',
                'resource' => 'registers',
                'action' => 'update',
                'description' => 'Can update cash register configurations',
            ],
            [
                'code' => 'registers.manage',
                'name' => 'Manage Registers',
                'module' => 'registers',
                'resource' => 'registers',
                'action' => 'manage',
                'description' => 'Can delete and manage cash registers',
            ],
            [
                'code' => 'pos_devices.view',
                'name' => 'View POS Devices',
                'module' => 'pos_devices',
                'resource' => 'pos_devices',
                'action' => 'view',
                'description' => 'Can view POS hardware devices and status',
            ],
            [
                'code' => 'pos_devices.create',
                'name' => 'Create POS Devices',
                'module' => 'pos_devices',
                'resource' => 'pos_devices',
                'action' => 'create',
                'description' => 'Can register new POS devices for an outlet',
            ],
            [
                'code' => 'pos_devices.update',
                'name' => 'Update POS Devices',
                'module' => 'pos_devices',
                'resource' => 'pos_devices',
                'action' => 'update',
                'description' => 'Can update POS device configurations',
            ],
            [
                'code' => 'pos_devices.manage',
                'name' => 'Manage POS Devices',
                'module' => 'pos_devices',
                'resource' => 'pos_devices',
                'action' => 'manage',
                'description' => 'Can activate, revoke, lock, and rotate secrets for POS devices',
            ],

            // ==========================================
            // 7. Products Catalog
            // ==========================================
            [
                'code' => 'products.view',
                'name' => 'View Products',
                'module' => 'products',
                'resource' => 'products',
                'action' => 'view',
                'description' => 'Can view products, variants, and product catalog details',
            ],
            [
                'code' => 'products.create',
                'name' => 'Create Products',
                'module' => 'products',
                'resource' => 'products',
                'action' => 'create',
                'description' => 'Can create new products and variants',
            ],
            [
                'code' => 'products.update',
                'name' => 'Update Products',
                'module' => 'products',
                'resource' => 'products',
                'action' => 'update',
                'description' => 'Can update products and variants',
            ],
            [
                'code' => 'products.delete',
                'name' => 'Delete Products',
                'module' => 'products',
                'resource' => 'products',
                'action' => 'delete',
                'description' => 'Can delete products and variants',
            ],
            [
                'code' => 'products.manage',
                'name' => 'Full Product Catalog Management',
                'module' => 'products',
                'resource' => 'products',
                'action' => 'manage',
                'description' => 'Can perform all product catalog management tasks',
            ],
            [
                'code' => 'categories.view',
                'name' => 'View Categories',
                'module' => 'categories',
                'resource' => 'categories',
                'action' => 'view',
                'description' => 'Can view product categories',
            ],
            [
                'code' => 'categories.create',
                'name' => 'Create Categories',
                'module' => 'categories',
                'resource' => 'categories',
                'action' => 'create',
                'description' => 'Can create product categories',
            ],
            [
                'code' => 'categories.update',
                'name' => 'Update Categories',
                'module' => 'categories',
                'resource' => 'categories',
                'action' => 'update',
                'description' => 'Can update product categories',
            ],
            [
                'code' => 'categories.delete',
                'name' => 'Delete Categories',
                'module' => 'categories',
                'resource' => 'categories',
                'action' => 'delete',
                'description' => 'Can delete product categories',
            ],
            [
                'code' => 'brands.view',
                'name' => 'View Brands',
                'module' => 'brands',
                'resource' => 'brands',
                'action' => 'view',
                'description' => 'Can view product brands',
            ],
            [
                'code' => 'brands.create',
                'name' => 'Create Brands',
                'module' => 'brands',
                'resource' => 'brands',
                'action' => 'create',
                'description' => 'Can create product brands',
            ],
            [
                'code' => 'brands.update',
                'name' => 'Update Brands',
                'module' => 'brands',
                'resource' => 'brands',
                'action' => 'update',
                'description' => 'Can update product brands',
            ],
            [
                'code' => 'brands.delete',
                'name' => 'Delete Brands',
                'module' => 'brands',
                'resource' => 'brands',
                'action' => 'delete',
                'description' => 'Can delete product brands',
            ],
            [
                'code' => 'units.view',
                'name' => 'View Units',
                'module' => 'units',
                'resource' => 'units',
                'action' => 'view',
                'description' => 'Can view units of measurement',
            ],
            [
                'code' => 'units.create',
                'name' => 'Create Units',
                'module' => 'units',
                'resource' => 'units',
                'action' => 'create',
                'description' => 'Can create units of measurement',
            ],
            [
                'code' => 'units.update',
                'name' => 'Update Units',
                'module' => 'units',
                'resource' => 'units',
                'action' => 'update',
                'description' => 'Can update units of measurement',
            ],
            [
                'code' => 'units.delete',
                'name' => 'Delete Units',
                'module' => 'units',
                'resource' => 'units',
                'action' => 'delete',
                'description' => 'Can delete units of measurement',
            ],
            [
                'code' => 'product_codes.view',
                'name' => 'View Product Codes',
                'module' => 'product_codes',
                'resource' => 'product_codes',
                'action' => 'view',
                'description' => 'Can view barcodes and SKUs',
            ],
            [
                'code' => 'product_codes.create',
                'name' => 'Create Product Codes',
                'module' => 'product_codes',
                'resource' => 'product_codes',
                'action' => 'create',
                'description' => 'Can create and generate barcodes and SKUs',
            ],
            [
                'code' => 'product_codes.delete',
                'name' => 'Delete Product Codes',
                'module' => 'product_codes',
                'resource' => 'product_codes',
                'action' => 'delete',
                'description' => 'Can delete barcodes and SKUs',
            ],
            [
                'code' => 'product_prices.view',
                'name' => 'View Product Prices',
                'module' => 'product_prices',
                'resource' => 'product_prices',
                'action' => 'view',
                'description' => 'Can view pricing tiers and history',
            ],
            [
                'code' => 'product_prices.create',
                'name' => 'Create Product Prices',
                'module' => 'product_prices',
                'resource' => 'product_prices',
                'action' => 'create',
                'description' => 'Can create product prices',
            ],
            [
                'code' => 'product_prices.update',
                'name' => 'Update Product Prices',
                'module' => 'product_prices',
                'resource' => 'product_prices',
                'action' => 'update',
                'description' => 'Can update product prices',
            ],
            [
                'code' => 'product_prices.delete',
                'name' => 'Delete Product Prices',
                'module' => 'product_prices',
                'resource' => 'product_prices',
                'action' => 'delete',
                'description' => 'Can delete product prices',
            ],
            [
                'code' => 'product_images.view',
                'name' => 'View Product Images',
                'module' => 'product_images',
                'resource' => 'product_images',
                'action' => 'view',
                'description' => 'Can view product gallery images',
            ],
            [
                'code' => 'product_images.create',
                'name' => 'Upload Product Images',
                'module' => 'product_images',
                'resource' => 'product_images',
                'action' => 'create',
                'description' => 'Can upload product images',
            ],
            [
                'code' => 'product_images.delete',
                'name' => 'Delete Product Images',
                'module' => 'product_images',
                'resource' => 'product_images',
                'action' => 'delete',
                'description' => 'Can delete product images',
            ],
            [
                'code' => 'labels.view',
                'name' => 'View Labels',
                'module' => 'labels',
                'resource' => 'labels',
                'action' => 'view',
                'description' => 'Can view label templates and print previews',
            ],
            [
                'code' => 'labels.print',
                'name' => 'Print Barcode Labels',
                'module' => 'labels',
                'resource' => 'labels',
                'action' => 'print',
                'description' => 'Can print product barcode labels',
            ],
            [
                'code' => 'labels.manage',
                'name' => 'Manage Label Templates',
                'module' => 'labels',
                'resource' => 'labels',
                'action' => 'manage',
                'description' => 'Can create, update, and delete label templates',
            ],

            // ==========================================
            // 8. Inventory (inventory_service)
            // ==========================================
            [
                'code' => 'inventory.view',
                'name' => 'View Inventory',
                'module' => 'inventory',
                'resource' => 'stock',
                'action' => 'view',
                'description' => 'Can view store stock levels',
            ],
            [
                'code' => 'inventory.update',
                'name' => 'Update Inventory',
                'module' => 'inventory',
                'resource' => 'stock',
                'action' => 'update',
                'description' => 'Can adjust stock levels',
            ],
            [
                'code' => 'inventory.admin',
                'name' => 'Inventory Module Administration',
                'module' => 'inventory',
                'resource' => 'inventory',
                'action' => 'admin',
                'description' => 'Full administrative control over inventory module',
            ],
            [
                'code' => 'inventory.warehouses.view',
                'name' => 'View Warehouses',
                'module' => 'inventory',
                'resource' => 'warehouses',
                'action' => 'view',
                'description' => 'Can view warehouse locations and zones',
            ],
            [
                'code' => 'inventory.warehouses.manage',
                'name' => 'Manage Warehouses',
                'module' => 'inventory',
                'resource' => 'warehouses',
                'action' => 'manage',
                'description' => 'Can create, edit, and configure warehouses',
            ],
            [
                'code' => 'inventory.stock.transfer',
                'name' => 'Transfer Stock',
                'module' => 'inventory',
                'resource' => 'stock',
                'action' => 'transfer',
                'description' => 'Can initiate and accept inter-warehouse/outlet stock transfers',
            ],
            [
                'code' => 'inventory.stock.count',
                'name' => 'Perform Stock Count',
                'module' => 'inventory',
                'resource' => 'stock',
                'action' => 'count',
                'description' => 'Can submit physical inventory stock counts',
            ],
            [
                'code' => 'inventory.procurement.view',
                'name' => 'View Purchase Orders',
                'module' => 'inventory',
                'resource' => 'procurement',
                'action' => 'view',
                'description' => 'Can view supplier purchase orders and requisitions',
            ],
            [
                'code' => 'inventory.procurement.order',
                'name' => 'Create Purchase Orders',
                'module' => 'inventory',
                'resource' => 'procurement',
                'action' => 'order',
                'description' => 'Can create and approve purchase orders for suppliers',
            ],
            [
                'code' => 'inventory.procurement.receive',
                'name' => 'Receive Goods',
                'module' => 'inventory',
                'resource' => 'procurement',
                'action' => 'receive',
                'description' => 'Can receive inbound shipments from suppliers',
            ],
            [
                'code' => 'inventory.audits.view',
                'name' => 'View Inventory Audits',
                'module' => 'inventory',
                'resource' => 'audits',
                'action' => 'view',
                'description' => 'Can review stock variance audit reports',
            ],
            [
                'code' => 'inventory.audits.reconcile',
                'name' => 'Reconcile Inventory',
                'module' => 'inventory',
                'resource' => 'audits',
                'action' => 'reconcile',
                'description' => 'Can authorize write-offs and stock reconciliations',
            ],
            [
                'code' => 'inventory.fulfillment.view',
                'name' => 'View Order Fulfillment',
                'module' => 'inventory',
                'resource' => 'fulfillment',
                'action' => 'view',
                'description' => 'Can view orders waiting for pick and pack',
            ],
            [
                'code' => 'inventory.fulfillment.pack',
                'name' => 'Pick & Pack Orders',
                'module' => 'inventory',
                'resource' => 'fulfillment',
                'action' => 'pack',
                'description' => 'Can mark order packages as picked and packed',
            ],
            [
                'code' => 'inventory.fulfillment.ship',
                'name' => 'Dispatch Shipments',
                'module' => 'inventory',
                'resource' => 'fulfillment',
                'action' => 'ship',
                'description' => 'Can create waybills and ship packages',
            ],

            // ==========================================
            // 9. Finance (finance_service)
            // ==========================================
            [
                'code' => 'finance.admin',
                'name' => 'Finance Module Administration',
                'module' => 'finance',
                'resource' => 'finance',
                'action' => 'admin',
                'description' => 'Full administrative control over finance module',
            ],
            [
                'code' => 'finance.dashboard.view',
                'name' => 'View Financial Dashboard',
                'module' => 'finance',
                'resource' => 'dashboard',
                'action' => 'view',
                'description' => 'Can view executive financial overview and metrics',
            ],
            [
                'code' => 'finance.accounts.view',
                'name' => 'View Chart of Accounts',
                'module' => 'finance',
                'resource' => 'accounts',
                'action' => 'view',
                'description' => 'Can view chart of accounts and balances',
            ],
            [
                'code' => 'finance.accounts.manage',
                'name' => 'Manage Chart of Accounts',
                'module' => 'finance',
                'resource' => 'accounts',
                'action' => 'manage',
                'description' => 'Can configure accounting ledger structures',
            ],
            [
                'code' => 'finance.gl.view',
                'name' => 'View General Ledger',
                'module' => 'finance',
                'resource' => 'gl',
                'action' => 'view',
                'description' => 'Can view journal entries and ledger logs',
            ],
            [
                'code' => 'finance.gl.post',
                'name' => 'Post Journal Entries',
                'module' => 'finance',
                'resource' => 'gl',
                'action' => 'post',
                'description' => 'Can create manual journal entries and adjustments',
            ],
            [
                'code' => 'finance.gl.close_period',
                'name' => 'Close Financial Periods',
                'module' => 'finance',
                'resource' => 'gl',
                'action' => 'close_period',
                'description' => 'Can lock and close monthly/annual fiscal periods',
            ],
            [
                'code' => 'finance.treasury.view',
                'name' => 'View Treasury & Cash',
                'module' => 'finance',
                'resource' => 'treasury',
                'action' => 'view',
                'description' => 'Can view bank accounts and cash holdings',
            ],
            [
                'code' => 'finance.treasury.manage_cash',
                'name' => 'Manage Cash Flows',
                'module' => 'finance',
                'resource' => 'treasury',
                'action' => 'manage_cash',
                'description' => 'Can allocate funds and manage liquidity',
            ],
            [
                'code' => 'finance.treasury.transfer',
                'name' => 'Execute Bank Transfers',
                'module' => 'finance',
                'resource' => 'treasury',
                'action' => 'transfer',
                'description' => 'Can authorize inter-bank transfers and deposits',
            ],
            [
                'code' => 'finance.reports.view',
                'name' => 'View Financial Reports',
                'module' => 'finance',
                'resource' => 'reports',
                'action' => 'view',
                'description' => 'Can view P&L, balance sheets, and cash flow reports',
            ],
            [
                'code' => 'finance.reports.export',
                'name' => 'Export Financial Reports',
                'module' => 'finance',
                'resource' => 'reports',
                'action' => 'export',
                'description' => 'Can export financial audits and tax filings',
            ],
            [
                'code' => 'finance.ar.view',
                'name' => 'View Accounts Receivable',
                'module' => 'finance',
                'resource' => 'ar',
                'action' => 'view',
                'description' => 'Can view invoices and customer credit balances',
            ],
            [
                'code' => 'finance.ar.invoice',
                'name' => 'Issue AR Invoices',
                'module' => 'finance',
                'resource' => 'ar',
                'action' => 'invoice',
                'description' => 'Can generate customer invoices and debit memos',
            ],
            [
                'code' => 'finance.ar.collect',
                'name' => 'Record AR Collections',
                'module' => 'finance',
                'resource' => 'ar',
                'action' => 'collect',
                'description' => 'Can apply received customer payments against invoices',
            ],
            [
                'code' => 'finance.ap.view',
                'name' => 'View Accounts Payable',
                'module' => 'finance',
                'resource' => 'ap',
                'action' => 'view',
                'description' => 'Can view vendor bills and pending obligations',
            ],
            [
                'code' => 'finance.ap.bills',
                'name' => 'Enter Vendor Bills',
                'module' => 'finance',
                'resource' => 'ap',
                'action' => 'bills',
                'description' => 'Can input supplier bills and credit notes',
            ],
            [
                'code' => 'finance.ap.approve',
                'name' => 'Approve Vendor Bills',
                'module' => 'finance',
                'resource' => 'ap',
                'action' => 'approve',
                'description' => 'Can approve supplier bills for disbursement',
            ],
            [
                'code' => 'finance.ap.pay',
                'name' => 'Disburse AP Payments',
                'module' => 'finance',
                'resource' => 'ap',
                'action' => 'pay',
                'description' => 'Can authorize and execute payments to suppliers',
            ],
            [
                'code' => 'finance.audits.view',
                'name' => 'View Financial Audits',
                'module' => 'finance',
                'resource' => 'audits',
                'action' => 'view',
                'description' => 'Can review internal and external financial audit trails',
            ],

            // ==========================================
            // 10. Point of Sale (pos_service)
            // ==========================================
            [
                'code' => 'pos.admin',
                'name' => 'POS Module Administration',
                'module' => 'pos',
                'resource' => 'pos',
                'action' => 'admin',
                'description' => 'Full administrative control over POS registers and terminals',
            ],
            [
                'code' => 'pos.access',
                'name' => 'Access POS Terminal',
                'module' => 'pos',
                'resource' => 'terminal',
                'action' => 'access',
                'description' => 'Can access cashier POS interface',
            ],
            [
                'code' => 'pos.checkout',
                'name' => 'Process Checkout',
                'module' => 'pos',
                'resource' => 'sales',
                'action' => 'checkout',
                'description' => 'Can process sales transactions',
            ],
            [
                'code' => 'pos.refund',
                'name' => 'Process Refund',
                'module' => 'pos',
                'resource' => 'sales',
                'action' => 'refund',
                'description' => 'Can issue sales refunds',
            ],
            [
                'code' => 'pos.void',
                'name' => 'Void Orders & Line Items',
                'module' => 'pos',
                'resource' => 'sales',
                'action' => 'void',
                'description' => 'Can void active items or complete orders',
            ],
            [
                'code' => 'pos.discount',
                'name' => 'Apply Manual Discount',
                'module' => 'pos',
                'resource' => 'sales',
                'action' => 'discount',
                'description' => 'Can apply manual discount overrides at checkout',
            ],
            [
                'code' => 'pos.shifts.open',
                'name' => 'Open Register Shift',
                'module' => 'pos',
                'resource' => 'shifts',
                'action' => 'open',
                'description' => 'Can open cashier shift and record opening float',
            ],
            [
                'code' => 'pos.shifts.close',
                'name' => 'Close Register Shift',
                'module' => 'pos',
                'resource' => 'shifts',
                'action' => 'close',
                'description' => 'Can reconcile and close register shifts (Z-report)',
            ],
            [
                'code' => 'pos.shifts.view',
                'name' => 'View Shift Reports',
                'module' => 'pos',
                'resource' => 'shifts',
                'action' => 'view',
                'description' => 'Can view active and closed register shift reports',
            ],
            [
                'code' => 'pos.reports.view',
                'name' => 'View POS Sales Reports',
                'module' => 'pos',
                'resource' => 'reports',
                'action' => 'view',
                'description' => 'Can view daily register turnover and sales summaries',
            ],
            [
                'code' => 'pos.reports.export',
                'name' => 'Export POS Reports',
                'module' => 'pos',
                'resource' => 'reports',
                'action' => 'export',
                'description' => 'Can export sales transactions and tender breakdowns',
            ],

            // ==========================================
            // 11. Human Resources (hr_service)
            // ==========================================
            [
                'code' => 'hr.admin',
                'name' => 'HR Module Administration',
                'module' => 'hr',
                'resource' => 'hr',
                'action' => 'admin',
                'description' => 'Full administrative control over HR, payroll, and staff',
            ],
            [
                'code' => 'hr.dashboard.view',
                'name' => 'View HR Dashboard',
                'module' => 'hr',
                'resource' => 'dashboard',
                'action' => 'view',
                'description' => 'Can view headcount, attendance, and payroll overview',
            ],
            [
                'code' => 'hr.employees.view',
                'name' => 'View Employee Profiles',
                'module' => 'hr',
                'resource' => 'employees',
                'action' => 'view',
                'description' => 'Can view employee directory and personal files',
            ],
            [
                'code' => 'hr.employees.create',
                'name' => 'Create Employee Records',
                'module' => 'hr',
                'resource' => 'employees',
                'action' => 'create',
                'description' => 'Can onboard and create new employee records',
            ],
            [
                'code' => 'hr.employees.update',
                'name' => 'Update Employee Records',
                'module' => 'hr',
                'resource' => 'employees',
                'action' => 'update',
                'description' => 'Can edit job titles, departments, and employee info',
            ],
            [
                'code' => 'hr.employees.delete',
                'name' => 'Terminate/Delete Employees',
                'module' => 'hr',
                'resource' => 'employees',
                'action' => 'delete',
                'description' => 'Can offboard and deactivate employee accounts',
            ],
            [
                'code' => 'hr.payroll.view',
                'name' => 'View Payroll Runs',
                'module' => 'hr',
                'resource' => 'payroll',
                'action' => 'view',
                'description' => 'Can view salary structures and wage calculation drafts',
            ],
            [
                'code' => 'hr.payroll.manage',
                'name' => 'Manage Payroll Configurations',
                'module' => 'hr',
                'resource' => 'payroll',
                'action' => 'manage',
                'description' => 'Can configure tax rates, allowances, and deductions',
            ],
            [
                'code' => 'hr.payroll.process',
                'name' => 'Process Payroll Calculation',
                'module' => 'hr',
                'resource' => 'payroll',
                'action' => 'process',
                'description' => 'Can run monthly payroll batch calculations',
            ],
            [
                'code' => 'hr.payroll.approve',
                'name' => 'Authorize Payroll Payouts',
                'module' => 'hr',
                'resource' => 'payroll',
                'action' => 'approve',
                'description' => 'Can provide final authorization for payroll transfers',
            ],
            [
                'code' => 'hr.benefits.view',
                'name' => 'View Benefits & Insurance',
                'module' => 'hr',
                'resource' => 'benefits',
                'action' => 'view',
                'description' => 'Can view company benefits and insurance plans',
            ],
            [
                'code' => 'hr.benefits.manage',
                'name' => 'Manage Employee Benefits',
                'module' => 'hr',
                'resource' => 'benefits',
                'action' => 'manage',
                'description' => 'Can enroll employees and configure benefit policies',
            ],
            [
                'code' => 'hr.recruitment.view',
                'name' => 'View Job Requisitions',
                'module' => 'hr',
                'resource' => 'recruitment',
                'action' => 'view',
                'description' => 'Can review job postings and applicant pipelines',
            ],
            [
                'code' => 'hr.recruitment.post',
                'name' => 'Create Job Openings',
                'module' => 'hr',
                'resource' => 'recruitment',
                'action' => 'post',
                'description' => 'Can publish job openings and review candidates',
            ],
            [
                'code' => 'hr.recruitment.hire',
                'name' => 'Extend Job Offers',
                'module' => 'hr',
                'resource' => 'recruitment',
                'action' => 'hire',
                'description' => 'Can extend offers and complete hiring workflows',
            ],
            [
                'code' => 'hr.compliance.view',
                'name' => 'View Compliance Records',
                'module' => 'hr',
                'resource' => 'compliance',
                'action' => 'view',
                'description' => 'Can view labor law compliance and certification status',
            ],
            [
                'code' => 'hr.compliance.manage',
                'name' => 'Manage HR Compliance Policies',
                'module' => 'hr',
                'resource' => 'compliance',
                'action' => 'manage',
                'description' => 'Can enforce workplace standards and legal compliance',
            ],
            [
                'code' => 'hr.self_service.view_payslip',
                'name' => 'View Personal Payslips',
                'module' => 'hr',
                'resource' => 'self_service',
                'action' => 'view_payslip',
                'description' => 'Can view individual monthly payslips',
            ],
            [
                'code' => 'hr.self_service.request_leave',
                'name' => 'Submit Leave Requests',
                'module' => 'hr',
                'resource' => 'self_service',
                'action' => 'request_leave',
                'description' => 'Can request annual, sick, or emergency leave',
            ],
            [
                'code' => 'hr.self_service.clock_in',
                'name' => 'Staff Attendance Clock In/Out',
                'module' => 'hr',
                'resource' => 'self_service',
                'action' => 'clock_in',
                'description' => 'Can clock in and out for work shifts',
            ],
            [
                'code' => 'hr.teams.view',
                'name' => 'View Team Reports',
                'module' => 'hr',
                'resource' => 'teams',
                'action' => 'view',
                'description' => 'Can view direct reports attendance and leave',
            ],
            [
                'code' => 'hr.teams.manage',
                'name' => 'Manage Team Schedules',
                'module' => 'hr',
                'resource' => 'teams',
                'action' => 'manage',
                'description' => 'Can approve team leave and manage work shifts',
            ],

            // ==========================================
            // 12. System Audit Logs
            // ==========================================
            [
                'code' => 'audit_logs.view',
                'name' => 'View System Audit Logs',
                'module' => 'audit_logs',
                'resource' => 'audit_logs',
                'action' => 'view',
                'description' => 'Can view general system audit trail logs',
            ],
            [
                'code' => 'audit_logs.export',
                'name' => 'Export System Audit Logs',
                'module' => 'audit_logs',
                'resource' => 'audit_logs',
                'action' => 'export',
                'description' => 'Can export system audit trail logs',
            ],
        ];

        foreach ($permissions as $permission) {
            $existing = Permission::where('code', $permission['code'])->first();
            Permission::updateOrCreate(
                [
                    'code' => $permission['code'],
                ],
                array_merge($permission, [
                    'uuid' => $existing?->uuid ?? (string) Str::uuid(),
                    'is_active' => true,
                ])
            );
        }

        $this->call(PermissionGroupSeeder::class);

        RbacCacheService::forgetRolesListCache();
    }
}