services:

  # ==========================================
  # Identity Laravel
  # ==========================================
  identity-service:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8001:8000"

    volumes:
      - .:/var/www/html
      - identity-vendor:/var/www/html/vendor

    depends_on:
      identity-mysql:
        condition: service_healthy

      identity-redis:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - identity-network
      - identity-smartpos-network

  # ==========================================
  # Identity MySQL
  # ==========================================
  identity-mysql:
    image: mysql:8.4

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "127.0.0.1:3307:3306"

    volumes:
      - identity-mysql-data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped

    networks:
      identity-network:
        aliases:
          - mysql

  # ==========================================
  # Identity Redis
  # ==========================================
  identity-redis:
    image: redis:8-alpine

    ports:
      - "127.0.0.1:6380:6379"

    volumes:
      - identity-redis-data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

    restart: unless-stopped

    networks:
      identity-network:
        aliases:
          - redis

  # ==========================================
  # Identity phpMyAdmin
  # ==========================================
  identity-phpmyadmin:
    image: phpmyadmin:5

    ports:
      - "127.0.0.1:8081:80"

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M

    depends_on:
      identity-mysql:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - identity-network

# ==========================================
# Networks
# ==========================================
networks:

  identity-network:
    driver: bridge

  identity-smartpos-network:
    name: smartpos-network
    external: true

# ==========================================
# Volumes
# ==========================================
volumes:

  identity-mysql-data:

  identity-redis-data:

  identity-vendor:
